# Specify the files and directories that should be ignored by HoundCI.
ignore:
  - node_modules/
  - coverage/
  - tests/
  - src/database/migrations 

# Specify the rules that HoundCI should follow for JavaScript files.
javascript:
  linter: eslint
  config_file: .eslintrc.json
  exclude_files:
    - test/**
    - spec/**
  extensions:
    - .js
  esversion: 6
