# Specify the rules that HoundCI should follow for JavaScript files.
javascript:
  linter: eslint
  config_file: .eslintrc.json
  exclude_files:
    - test/**
    - spec/**
  extensions:
    - .js
  esversion: 6