version: 2.1

orbs:
  node: circleci/node@4.7

# Define jobs
jobs:
  build:
    # Set up the job environment
    docker:
      - image: circleci/node:16.10

    # Define the steps to run in this job
    steps:
      # Checkout the code from the GitHub repository
      - checkout

      # Install dependencies
      - run: npm install

      # Run the build command
      - run: npm run build

  test:
    # Set up the job environment
    docker:
      - image: circleci/node:16.10

    # Define the steps to run in this job
    steps:
      # Checkout the code from the GitHub repository
      - checkout

      # Install dependencies
      - run: npm install

      # Run the tests
      - run: npm run migrate:all
      
      - run: npm test

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - test
