version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:16
    environment:
      COVERALLS_REPO_TOKEN: 4VrPrLnrpX85LAe2nPMZdwad6lALo29OX
      COVERALLS_REPO_NAME: e-comm-team-brogrammers-bn
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Install npm dev dependencies
          command: npm install mocha c8 chai-http chai coveralls
      - run:
          name: Run migrations
          command: npm run migrate:all
      - run:
          name: Run Unit Tests & coverage
          command: npm run coverage && ./node_modules/.bin/c8 report --reporter=text-lcov | ./node_modules/.bin/coveralls

workflows:
  build_tests:
    jobs:
      - run_tests
